// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pokedex.Infrastructure;

#nullable disable

namespace Pokedex.Infrastructure.Migrations
{
    [DbContext(typeof(PokedexDbContext))]
    [Migration("20260610072203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pokedex.Domain.Entities.PokemonGeneric", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("Attack")
                        .HasColumnType("integer")
                        .HasColumnName("attack");

                    b.Property<int?>("Defense")
                        .HasColumnType("integer")
                        .HasColumnName("defense");

                    b.Property<int?>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<int?>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<bool?>("Legendary")
                        .HasColumnType("boolean")
                        .HasColumnName("legendary");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("Sp_Attack")
                        .HasColumnType("integer")
                        .HasColumnName("spattack");

                    b.Property<int?>("Sp_Defense")
                        .HasColumnType("integer")
                        .HasColumnName("spdefense");

                    b.Property<int?>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int?>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<string>("Type1")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type1");

                    b.Property<string>("Type2")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type2");

                    b.HasKey("Number");

                    b.ToTable("pokemon_generic", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
